# Generated by Django 3.0.7 on 2020-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='Language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='inventor',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
