# Generated by Django 3.0.7 on 2020-07-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studId', models.CharField(max_length=10)),
                ('studName', models.CharField(max_length=30)),
                ('branch', models.CharField(choices=[('CSE', 'cse'), ('ECE', 'ece'), ('MECH', 'mech'), ('IT', 'it')], max_length=20)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
